SQL_DB_SYSTEM = "postgresql"  # SQL DATABASE SYSTEM
DB_USERNAME = "postgres"  # DATABASE USERNAME
DB_PASSWORD = "gk"  # DATABASE PASSWORD
DB_HOST = "localhost"  # DATABASE HOST
DB_PORT = "5432"  # DATABASE PORT
DB_SERVER = "postgres"  # DATABASE SERVER NAME
